models:
  clip: "ViT-B/32"
  blip: "microsoft/git-large"
  llm: "distilgpt2"
data:
  image_dir: "data/images"
  temp_dir: "data/temp"
  max_results: 20
  batch_size: 4
session:
  timeout_seconds: 1800 